// Generated by LiveScript 1.3.1
/*@source p0ne.end.ls */
_.defer(function(){
  var remaining, name, ref$, m;
  remaining = 1;
  for (name in ref$ = p0ne.modules) {
    m = ref$[name];
    if (m.loading) {
      remaining++;
      m.loading.always(moduleLoaded);
    }
  }
  moduleLoaded();
  if (remaining) {
    console.info(getTime() + " [p0ne] " + plural(remaining, 'module') + " still loading");
  }
  function moduleLoaded(m){
    var noCollapsedGroup, name, ref$;
    if (--remaining === 0) {
      console.error = error_;
      console.warn = warn_;
      console.groupEnd();
      console.info("[p0ne] initialized!");
      if (errors) {
        console.error("[p0ne] There have been " + errors + " errors");
      }
      if (warnings) {
        console.warn("[p0ne] There have been " + warnings + " warnings");
      }
      noCollapsedGroup = true;
      for (name in ref$ = p0ne.modules) {
        m = ref$[name];
        if (m.disabled && !m.settings && !(m.moderator && user.isStaff)) {
          if (noCollapsedGroup) {
            console.groupCollapsed("[p0ne] there are disabled modules which are hidden from the settings");
            noCollapsedGroup = false;
          }
          console.warn("\t" + name, m);
        }
      }
      if (!noCollapsedGroup) {
        console.groupEnd();
      }
      if (typeof appendChat == 'function') {
        appendChat("<div class='cm p0ne-notif p0ne-notif-loaded'>plug_p0ne v" + p0ne.version + " loaded " + (typeof getTimestamp == 'function' ? getTimestamp() : void 8) + "</div>");
      }
      return console.timeEnd("[p0ne] completly loaded");
    }
  }
});
